version: '3'

services:
  app:
    build: .
    restart: always
    image: scr_bot
    command: python3 app.py
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    ports:
      - ${WEBHOOK_PORT}:${WEBHOOK_PORT}

